#!/bin/bash
# =============================================================
# CGS Kitchen POS — Kiosk Update Script (Raspberry Pi 5)
#
# 1. Hard-resets local working copy to match origin/main
# 2. Regenerates .env from /etc/celtech/env (Vite needs it
#    present BEFORE the build — VITE_* vars are inlined at
#    build time, not read at runtime)
# 3. Runs `npm ci && npm run build` to (re)emit dist/
#
# This differs from the driver app: the driver app writes a
# runtime config.js that the page reads on load, so it never
# rebuilds. A Vite app bakes its config in at build time, so
# the env must exist first and the app must be rebuilt.
# =============================================================

set -e

APP_DIR="/home/druid-mobile/celtech-pos"
LOG_FILE="/home/druid-mobile/update.log"
ENV_FILE="/etc/celtech/env"
ENV_OUT="$APP_DIR/.env"
BRANCH="main"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "-----------------------------------"
log "Starting CGS Kitchen POS software update"

if [ ! -d "$APP_DIR/.git" ]; then
    log "ERROR: $APP_DIR is not a git repository. Aborting."
    exit 1
fi

cd "$APP_DIR"

# ---- Wait for network (up to 30 seconds) -------------------
log "Waiting for network..."
WAIT=0
NETWORK_OK=1
until ping -c 1 -W 2 8.8.8.8 &>/dev/null; do
    WAIT=$((WAIT + 2))
    if [ $WAIT -ge 30 ]; then
        log "WARNING: No network after 30s. Skipping git update; will build existing checkout."
        NETWORK_OK=0
        break
    fi
    sleep 2
done

# ---- Pull latest --------------------------------------------
NEED_BUILD=0
if [ $NETWORK_OK -eq 1 ]; then
    log "Network ready after ${WAIT}s."
    log "Fetching from origin..."
    git fetch origin "$BRANCH" >> "$LOG_FILE" 2>&1

    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse "origin/$BRANCH")

    if [ "$LOCAL" = "$REMOTE" ]; then
        if [ -n "$(git status --porcelain)" ]; then
            log "Local modifications detected, resetting to clean state..."
            git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
            NEED_BUILD=1
        fi
        log "Already up to date ($(git rev-parse --short HEAD))."
    else
        log "Update available: $(git rev-parse --short HEAD) -> $(git rev-parse --short origin/$BRANCH)"
        git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
        log "Updated to: $(git rev-parse --short HEAD)"
        NEED_BUILD=1
    fi
fi

# ---- Generate .env from environment file (always) ----------
log "Generating .env from $ENV_FILE..."
if [ ! -f "$ENV_FILE" ]; then
    log "WARNING: $ENV_FILE not found. .env will have empty values."
    API_BASE_URL=""
    API_KEY=""
    POS_ACTOR=""
else
    set -a
    source "$ENV_FILE"
    set +a
fi

# Map /etc/celtech/env names -> VITE_ names the app expects.
NEW_ENV="$(cat <<EOF
# Auto-generated by update.sh — do not edit manually.
# Values come from $ENV_FILE
VITE_API_BASE_URL=${API_BASE_URL:-}
VITE_API_KEY=${API_KEY:-}
VITE_POS_ACTOR=${POS_ACTOR:-pos-terminal}
EOF
)"

# Only rewrite + rebuild if the env actually changed (avoids a
# pointless ~minute rebuild on every boot).
if [ ! -f "$ENV_OUT" ] || [ "$NEW_ENV" != "$(cat "$ENV_OUT")" ]; then
    echo "$NEW_ENV" > "$ENV_OUT"
    log ".env changed — build required."
    NEED_BUILD=1
else
    log ".env unchanged."
fi

# ---- Report which keys are populated -----------------------
if [ -n "${API_BASE_URL:-}" ]; then
    log "VITE_API_BASE_URL = ${API_BASE_URL}"
else
    log "WARNING: API_BASE_URL is empty — POS cannot reach the backend."
fi
if [ -n "${API_KEY:-}" ]; then
    log "VITE_API_KEY present (${#API_KEY} chars)."
else
    log "WARNING: API_KEY is empty — all /api/** calls will be rejected (401)."
fi

# ---- Build if needed ----------------------------------------
if [ ! -d "$APP_DIR/dist" ]; then
    log "No dist/ present — build required."
    NEED_BUILD=1
fi

if [ $NEED_BUILD -eq 1 ]; then
    if [ $NETWORK_OK -eq 0 ] && [ ! -d "$APP_DIR/node_modules" ]; then
        log "ERROR: build needed but offline and node_modules missing. Keeping any existing dist/."
    else
        log "Building app (npm ci && npm run build)..."
        if [ $NETWORK_OK -eq 1 ]; then
            npm ci >> "$LOG_FILE" 2>&1 || { log "ERROR: npm ci failed."; exit 1; }
        fi
        npm run build >> "$LOG_FILE" 2>&1 || { log "ERROR: npm run build failed."; exit 1; }
        log "Build complete -> $APP_DIR/dist"
    fi
else
    log "No rebuild needed (no code or env change, dist/ present)."
fi

log "Update complete."
log "-----------------------------------"
exit 0
